#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Background scheduler for HS300 V1.5 paper trading.

Spawns a single thread that wakes up periodically. During China A-share
trading hours (09:30-11:30 + 13:00-15:00 Beijing time) it calls
live_signal_engine.live-once for today, refreshing the SQLite DB so the
dashboard shows up-to-date signals.

Default cadence is 5 minutes during market hours and 30 minutes outside.
Outside-market polls are infrequent because all they do is detect when
markets reopen; once an exit-only state is detected we skip until the
next session.

The scheduler is designed to run in the same process as the Flask
dashboard (called from dashboard.py). It is also runnable standalone
(`python scheduler.py`) for local testing.

Wall-clock anti-leak property:
- Each tick records the wall-clock time it ran.
- We only ever process minutes whose end-of-bar timestamp is strictly
  before the current wall-clock time.
- Akshare returns minutes 09:30..15:00. The engine processes them in
  minute_idx order. At any tick, the engine works on data that was
  generated by the market in the past.
"""

from __future__ import annotations

import logging
import os
import sys
import threading
import time
import traceback
from datetime import datetime
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "paper_trading"))

from live_signal_engine import (
    DEFAULT_DB,
    derive_fold_thresholds,
    fetch_via_akshare_into_overlay,
    init_db,
    log_run,
    stream_live_day,
)
from data_source_akshare import AkshareDataSource

logger = logging.getLogger("hs300_scheduler")
logger.setLevel(logging.INFO)
if not logger.handlers:
    h = logging.StreamHandler()
    h.setFormatter(logging.Formatter("%(asctime)s [%(name)s] %(message)s"))
    logger.addHandler(h)


def is_market_hours(now: pd.Timestamp) -> bool:
    """A-share trading hours, 09:30-11:30 and 13:00-15:00 Beijing time, weekdays."""
    if now.weekday() >= 5:
        return False
    h, m = now.hour, now.minute
    if (h == 9 and m >= 30) or (10 <= h < 11) or (h == 11 and m <= 30):
        return True
    if (13 <= h < 15) or (h == 15 and m == 0):
        return True
    return False


def in_post_market_window(now: pd.Timestamp) -> bool:
    """5 minutes after close: do one final pull to catch the last bar."""
    if now.weekday() >= 5:
        return False
    h, m = now.hour, now.minute
    return h == 15 and 0 < m <= 5


def beijing_now() -> pd.Timestamp:
    return pd.Timestamp.now(tz="Asia/Shanghai").tz_localize(None)


def run_one_cycle(db_path: Path):
    """Fetch via akshare and stream-process the latest trading day."""
    from run_hs300_phase1_5m_eval import Config as FeatureConfig
    from run_hs300_downside_walkforward import (
        PROJECT_ROOT,
        list_trade_dates,
        load_weight_table,
        load_industry_map,
    )
    from compute_multiproj_features import Config as MultiprojConfig

    src = AkshareDataSource(REPO_ROOT / "paper_trading" / "akshare_cache")
    target_date = src.latest_trading_date()
    logger.info(f"cycle target_date={target_date}")

    # Fetch and overlay
    overlay_stock, overlay_etf = fetch_via_akshare_into_overlay(target_date)

    # On Render the project-root artifact is not present; fall back to the
    # shipped copy under paper_trading/.
    industry_map_local = PROJECT_ROOT / "artifacts/ashare_t1_xgb_stfree_mcap10_500_v2_fullrun/industry_map_baostock.parquet"
    industry_map_shipped = REPO_ROOT / "paper_trading/industry_map_baostock.parquet"
    industry_map_path = str(industry_map_local if industry_map_local.exists() else industry_map_shipped)

    cfg_feature = FeatureConfig(
        stock_data_dir=str(PROJECT_ROOT / "stock_data"),
        etf_data_dir=str(PROJECT_ROOT / "ETF data core7 precise"),
        weights_csv="",
        industry_map_path=industry_map_path,
        output_dir=str(REPO_ROOT / "paper_trading" / "_tmp"),
        amount_min=100000.0,
        min_active_constituents=120,
    )
    live_cfg_feature = FeatureConfig(
        stock_data_dir=str(overlay_stock),
        etf_data_dir=str(overlay_etf),
        weights_csv="",
        industry_map_path=cfg_feature.industry_map_path,
        output_dir=cfg_feature.output_dir,
        amount_min=100000.0,
        min_active_constituents=120,
    )
    live_cfg_multiproj = MultiprojConfig(
        stock_data_dir=str(overlay_stock),
        etf_data_dir=str(overlay_etf),
        industry_map_path=cfg_feature.industry_map_path,
    )

    weights_by_date = load_weight_table(str(REPO_ROOT / "research/strategy_lab/data/hs300_daily_weights/hs300_weights_2025-01-01_2026-04-30.csv"))
    weight_dates_sorted = sorted(weights_by_date.keys())
    industry = load_industry_map(cfg_feature.industry_map_path)

    all_dates = list_trade_dates(Path(cfg_feature.stock_data_dir), Path(cfg_feature.etf_data_dir), "2024-01-01", "2026-12-31")
    history = sorted([h for h in all_dates if pd.Timestamp(h).normalize() < pd.Timestamp(target_date).normalize()])

    fold = derive_fold_thresholds(target_date, train_days=120)

    conn = init_db(db_path)
    conn.execute("DELETE FROM trades WHERE date=?", (target_date,))
    conn.execute("DELETE FROM signals WHERE date=?", (target_date,))
    conn.commit()

    stream_live_day(
        target_date, cfg_feature, live_cfg_feature, live_cfg_multiproj,
        weights_by_date, weight_dates_sorted, industry,
        fold, conn, history_dates=history,
    )
    log_run(conn, target_date, "scheduler", "cycle complete")
    conn.close()
    logger.info(f"cycle done for {target_date}")


def scheduler_loop(db_path: Path, market_hours_interval: int = 300, off_hours_interval: int = 1800):
    """Sleep loop that calls run_one_cycle() at the configured cadence.

    market_hours_interval: seconds between cycles during 09:30-15:00 Beijing.
    off_hours_interval: seconds between cycles outside market hours.
    """
    last_cycle_target_date: str | None = None
    last_cycle_at: pd.Timestamp | None = None
    while True:
        try:
            now = beijing_now()
            in_market = is_market_hours(now)
            in_post = in_post_market_window(now)
            should_run = in_market or in_post or last_cycle_target_date is None
            if should_run:
                logger.info(f"tick at {now} (market_hours={in_market}); running cycle")
                run_one_cycle(db_path)
                last_cycle_at = now
            else:
                logger.info(f"tick at {now} (off-hours); sleeping")
            interval = market_hours_interval if (in_market or in_post) else off_hours_interval
        except Exception as exc:
            logger.error(f"scheduler error: {exc}")
            traceback.print_exc()
            interval = 300  # back off on errors
        time.sleep(interval)


def start_in_background(db_path: Path = DEFAULT_DB) -> threading.Thread:
    """Start the scheduler in a daemon thread. Safe to call from web app
    startup. The thread terminates when the process exits."""
    t = threading.Thread(target=scheduler_loop, args=(db_path,), daemon=True, name="hs300_scheduler")
    t.start()
    logger.info(f"scheduler started in background, db={db_path}")
    return t


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default=str(DEFAULT_DB))
    parser.add_argument("--once", action="store_true", help="Run one cycle and exit")
    args = parser.parse_args()
    if args.once:
        run_one_cycle(Path(args.db))
    else:
        scheduler_loop(Path(args.db))
